### ISSUE TITLE
Fix ghosting issues

### ISSUE THREAD

**Issue by PotatoOfDoom** [PotatoOfDoom/CyberFSR2#1]
Steps to fix ghosting issues
- [ ] Make sure the reactive mask/ BiasCurrentColor mask conversion works correctly.
- [ ] Fix vehicle ghosting by injecting info from the stencil buffer into the reactive map. [More info here](https://aws.amazon.com/de/blogs/gametech/anti-ghosting-with-temporal-anti-aliasing/)
- [ ] Find a solution for transparent and holographic objects.

**Comment by doktorsleepelss** [comment]
The  ghosting can get pretty bad while driving even in officially supported games like Farming simulator 2.
https://gfycat.com/serenedangerousamericanredsquirrel

and in the City Samples demo with the FSR 2.0 plugin.
https://gfycat.com/famousunitedgrasshopper

Isn't this just inherit to the FSR 2.0's algorithm?

**Comment by coytb** [comment]
Have you tried using the DLSS debug dll and the debug view in games? In Cyberpunk I don't see the reactive mask usage except for some particle effects like sparks. The ghosting on NPCs when walking around seems to be a different issue than the ghosting of player car.

**Comment by spajdrEX** [comment]
So how does it look with ghosting issue, is there anything that can be done about it?
