### ISSUE TITLE
Working with UE4 games?

### ISSUE THREAD

**Issue by TheRazerMD** [PotatoOfDoom/CyberFSR2#14]
Anyone tried modifying it for any UE4 game? Tried using the DL2 version that worked on other games (like Metro Exodus and Guardians) but no luck so far (tried on Deep Rock Galactic and Ready or Not). Might be a problem regarding the typical UE4 folder structuring - the DLSS dll is hidden behind atleast 3 or 4 subfolders from the game exe. Tried symlinks and hard links, but no dice.

**Comment by lnfecteDru** [comment]
I believe, both of these games use DirectX 11 (as per System Requirements in the according Steam pages), while this project atm works with DirectX 12

**Comment by TheRazerMD** [comment]
Both games have DX11 and DX12 as a launch option, so that part should not be the problem.

**Comment by TheRazerMD** [comment]
@xv0t probably has some special GPU checks that need patching out

@ronoverdrive yeah, that’s why I mentioned the 2 games above. DRG and RoN, for example, don’t have EAC to complicate things.

**Comment by lnfecteDru** [comment]
I kinda managed to activate the DLSS option in Deep Rock Galactic, but for me it gives a lot of visual glitches. But anyway, I had to place JMP (0xEB) in 0xEC4DBF to skip GPU check (corresponds to "else if (!IsRHIDeviceNVIDIA())" line in the plugin source code, particularly in file "DLSS.cpp"). Not sure yet how to patch it, cause for some reason my proxy dll is injected during debugging session but skipped during clean start.

**Comment by TheRazerMD** [comment]
@lnfecteDru Great work! Yeah, there were mentions of that string in the Discord server, found being mentioned in the DLSS Programming guide and then later while randomly searching interesting strings. 

Also an interesting thing that may or may not be useful. After the latest commits regarding UE compatibility, I tried the DXVK+VKD3D meme spoof to RTX 3080 on my RX580 again. And now, there were no driver version error dialogue, and the DLSS option actually got exposed and it's working. Well, "working" as its got visual artifacts everywhere, as you've mentioned.

@PotatoOfDoom mentioned you'd have to play around with FoV and Depth values to get it working better, Also mentioned the common UE4/5 depth values are:  NearPlane: 10.0  FarPlane: 1010.0

**Comment by lnfecteDru** [comment]
For Ghostwire this works as well even though it was a bit harder to find, cause there were no such string. The address is 0x12C3FDB where 6 bytes need to be replaced with NOPs. The game has visual glitches too, but different ones.

**Comment by TheRazerMD** [comment]
Could you show me a screen of the Ghostwire address? I'm trying to look for it in Ready or Not, but it also doesn't have this string. Neither does Chivalry 2.

**Comment by lnfecteDru** [comment]
> Could you show me a screen of the Ghostwire address? I'm trying to look for it in Ready or Not, but it also doesn't have this string. Neither does Chivalry 2.

Sure, here it is!
![ghostwire_assembly](https://user-images.githubusercontent.com/11487095/182045460-cbd57505-df6b-49a2-9a1d-bd8a41179c2f.png)

I was searching for this particular section:
```
...
else if (!bLoadLibraries)
{
	UE_LOG(LogDLSS, Log, TEXT("NVIDIA NGX library loading has been disabled with r.NGX.Enable=0"));
	DLSSSupport = EDLSSSupport::NotSupported;
}
else
{
	// This one
	const bool bIsDX12 = (RHIName == TEXT("D3D12")) && GetDefault<UDLSSSettings>()->bEnableDLSSD3D12;
	const bool bIsDX11 = (RHIName == TEXT("D3D11")) && GetDefault<UDLSSSettings>()->bEnableDLSSD3D11;
	const bool bIsVulkan = (RHIName == TEXT("Vulkan")) && GetDefault<UDLSSSettings>()->bEnableDLSSVulkan;
...
```
Even though there are no log strings in Ghostwire, there are still strings "D3D12", "D3D11" and "Vulkan". And I was looking for jumps to this section.

**Comment by lnfecteDru** [comment]
In case of Ready or Not - the address is 0xABDBBF where you need to replace 1 byte with 0xEB (which is JMP). I'll attach a screenshot of the debugger later.

**Comment by TheRazerMD** [comment]
@lnfecteDru You won't believe it, but I actually managed to patch it myself! Saw your screen regarding D3D12, found it, tried the JNE to JMP and managed to bypass it. Then I came here, and saw you already posted the screenshot XD

Thanks for all the help. Will try it on other UE4 games too.

**Comment by TheRazerMD** [comment]
Managed to find it for The Ascent too!

Change JNE to JMP on RVA 0xF95596 and it should work.

![Screenshot_1](https://user-images.githubusercontent.com/78263903/182048747-1bd8e5be-b516-4c02-86c5-d248cd063ea3.png)

This is how it originally looks like

**Comment by TheRazerMD** [comment]
@lnfecteDru here's an interesting found. It seems CyberFSR2 does work with some UE4 games.

Hellblade Enhanced and Chivalry 2 (bypassed EAC launch and tried on offline mode) are both UE4 games and have no GPU check. And it works just fine with both games, no artifacting. But other UE4 games with RTX/GPU Checks still keep on artifacting.
Interesting, to say the least.

[Hellblade Enhanced](https://imgsli.com/MTIxMTE3)
[Chivalry 2](https://imgsli.com/MTIxMTI2)

**Comment by lnfecteDru** [comment]
> @lnfecteDru here's an interesting find. It seems CyberFSR2 does work with some UE4 games.
> 
> Hellblade Enhanced and Chivalry 2 (bypassed EAC launch and tried on offline mode) are both UE4 games and have no GPU check. And it works just fine with both games, no artifacting. But other UE4 games with RTX/GPU Checks still keep on artifacting.
> Interesting, to say the least.
> 
> [Hellblade Enhanced](https://imgsli.com/MTIxMTE3)
> [Chivalry 2](https://imgsli.com/MTIxMTI2)

Interesting indeed, I'll have a look.

**Comment by lnfecteDru** [comment]
Looks like disabling dilated motion vectors (r.NGX.DLSS.DilateMotionVectors 0) fixes the strange ghosting-like artifacts. Blinks, however, are still there.

**Comment by TheRazerMD** [comment]
@lnfecteDru Going by Discord, that option fixed the ghosting for both Ghostrunner and Chorus. But now comes the fun part.
The tester trying it out for Ghostrunner has a Pascal GPU (1050Ti), did not need GPU Check bypass (I suspect it requires only Nvidia GPU, not RTX, despite the in-game note saying RTX lol), mod works great after using that command. 
Meanwhile, I tried my RX580 - needed to bypass the GPU check - DLSS option exposed - artifacting like crazy, even with the command.

The Ascent on 1660Ti apparently also works fine, even with the required GPU Check bypass - meanwhile it artifacts on Radeon as usual.

Seems to me Radeon isn't getting parsed correct data when the GPU Check is present in UE4, for whatever reason.

**Comment by lnfecteDru** [comment]
Also, CVars may be applied without patching by putting it in `Engine.ini`:
```
[SystemSettings]
r.NGX.DLSS.DilateMotionVectors=0
```

So there's no really need to patch it.

About the glitch part, probably there are some nvidia driver calls. I'll try to find something.

**Comment by TheRazerMD** [comment]
Forgot to mention in the last comment, but yes, pretty sure there's no need for patching as adding the command to Engine.ini should make it work everywhere. 

> (idk tho if section name or ini-file matter)

ini files matter for UE4, so it will only work if you put that whole command (with the SystemSettings part too) specifically in Engine.ini in WindowsNoEditor folder where the game config files are located

**Comment by lnfecteDru** [comment]
`r.SceneColorFormat=5` fixed it for me. Can anybody check it as well?

**Comment by TheRazerMD** [comment]
Give me a few mins and I can check it out.

**Comment by TheRazerMD** [comment]
@lnfecteDru Potato on Discord:

"sry I am super busy rn. the ue4 fix you guys found seems to be caused by a bug in fsr 2: https://github.com/GPUOpen-Effects/FidelityFX-FSR2/issues/39
(Probably already fixed in the internal tree 🙄). I'll add the fix to my fsr2 fork as soon as I have access to a pc again"

**Comment by lnfecteDru** [comment]
> @lnfecteDru Potato on Discord:
> 
> "sry I am super busy rn. the ue4 fix you guys found seems to be caused by a bug in fsr 2: [GPUOpen-Effects/FidelityFX-FSR2#39](https://github.com/GPUOpen-Effects/FidelityFX-FSR2/issues/39) (Probably already fixed in the internal tree 🙄). I'll add the fix to my fsr2 fork as soon as I have access to a pc again"

Not really sure if it will help in this case, cause it looks like motion vector scale, sent by the engine, is equal to 1 regardless of settings:
![image](https://user-images.githubusercontent.com/11487095/185456296-0e77f372-88ac-4412-99c0-285f09efadaf.png)

**Comment by oscarbg** [comment]
Hi,
are someone interested in help fixing the UE5 5.1 City demo.. @lnfecteDru @TheRazerMD  ?
https://www.dsogaming.com/news/the-matrix-awakens-megacity-unreal-engine-5-1-available-for-download/
download this UE5.1 demo:
https://drive.google.com/file/d/1eQ_Oav8pxMJ-55qwwyRurjS_dyKgFGqZ/view
seems have some checks..
log:
```
[2022.08.27-05.35.35:282][  0]LogDLSS: FDLSSModule::StartupModule Enter
[2022.08.27-05.35.35:282][  0]LogDLSS: PluginBaseDir ../../../CitySample/Plugins/DLSS
[2022.08.27-05.35.35:302][  0]LogDLSS: NGXBinariesDir ../../../CitySample/Plugins/DLSS/Binaries/ThirdParty/Win64/
[2022.08.27-05.35.35:303][  0]LogDLSS: GDynamicRHIName NVIDIA D3D12
[2022.08.27-05.35.35:313][  0]LogDLSS: Plugin settings: NGXAppId = 0
[2022.08.27-05.35.35:317][  0]LogDLSS: Warning: NGX Application ID not specified, using the Project ID by default.
[2022.08.27-05.35.35:319][  0]LogDLSSNGXRHI: FNGXRHIModule::StartupModule Enter
[2022.08.27-05.35.35:321][  0]LogDLSSNGXRHI: FNGXRHIModule::StartupModule Leave
[2022.08.27-05.35.35:327][  0]LogDLSSNGXRHI: Searching for custom and generic DLSS binaries
[2022.08.27-05.35.35:328][  0]LogDLSSNGXRHI: NVIDIA NGX DLSS binary nvngx_dlss.dll not found in search path E:\a4\CitySample_51_DLSS_Cinematic\CitySample\Binaries\ThirdParty\NVIDIA\NGX\Win64\
[2022.08.27-05.35.35:329][  0]LogDLSSNGXRHI: NVIDIA NGX DLSS binary nvngx_dlss.dll not found in search path E:\a4\CitySample_51_DLSS_Cinematic\CitySample\Binaries\Win64\Binaries\ThirdParty\NVIDIA\NGX\Win64\
[2022.08.27-05.35.35:330][  0]LogDLSSNGXRHI: NVIDIA NGX DLSS binary nvngx_dlss.dll found in search path E:\a4\CitySample_51_DLSS_Cinematic\CitySample\Plugins\DLSS\Binaries\ThirdParty\Win64\
[2022.08.27-05.35.35:332][  0]LogDLSSNGX: [SDK]: [2022-08-27 07:35:35] [NGXSafeInitializeLog:130] App logging hooks successfully initialized
[2022.08.27-05.35.35:346][  0]LogDLSSNGX: [SDK]: [2022-08-27 07:35:35] [NGXGetPathUsingQAI:127] Path to driverStore found using QAI: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_800c5375bcee0134
[2022.08.27-05.35.35:883][  0]LogDLSSNGX: [Core]: [2022-08-27 07:35:35] [NGXSafeInitializeLog:130] App logging hooks successfully initialized
[2022.08.27-05.35.35:996][  0]LogDLSSNGX: [Core]: [2022-08-27 07:35:35] [NGXCheckHardwareSupportUsingINF:212] error: unsupported hardware detected
[2022.08.27-05.35.36:002][  0]LogDLSSNGXD3D12RHI: NVSDK_NGX_D3D12_Init_with_ProjectID(ProjectID = 914301364FA2BD41AB81DA86AC490783, EngineVersion=5.1, APIVersion = 0x14, Device=0000012D6C4A1040) -> (3134193665 NVSDK_NGX_Result_FAIL_FeatureNotSupported)
[2022.08.27-05.35.36:086][  0]LogDLSSNGX: [Core]: [2022-08-27 07:35:36] [NGXCheckHardwareSupportUsingINF:212] error: unsupported hardware detected
[2022.08.27-05.35.36:106][  0]LogDLSSNGXD3D12RHI: NVSDK_NGX_D3D12_Init_with_ProjectID(ProjectID = 914301364FA2BD41AB81DA86AC490783, EngineVersion=5.1, APIVersion = 0x13, Device=0000012D6C4A1040) -> (3134193665 NVSDK_NGX_Result_FAIL_FeatureNotSupported)
[2022.08.27-05.35.36:111][  0]LogDLSSNGXD3D12RHI: NVSDK_NGX_D3D12_Init (Log C:/Users/rtfss/AppData/Local/CitySample/Saved/Logs/NGX/NGX_2022.08.27-07.35.35_478E6EB7483B6E0FFCA9559322110D8C) -> (3134193665 NVSDK_NGX_Result_FAIL_FeatureNotSupported)
[2022.08.27-05.35.36:113][  0]LogDLSS: DLSS not supported by the NVIDIA D3D12 RHI in the NGXD3D12RHI module at runtime
[2022.08.27-05.35.36:113][  0]LogDLSS: NVIDIA NGX DLSS supported 0
[2022.08.27-05.35.36:114][  0]LogDLSS: FDLSSModule::StartupModule Leave
```

**Comment by lnfecteDru** [comment]
> Hi, are someone interested in fixing the UE5 5.1 City demo (with DLSS support)?.. @lnfecteDru @TheRazerMD ? https://www.dsogaming.com/news/the-matrix-awakens-megacity-unreal-engine-5-1-available-for-download/ download this UE5.1 demo: https://drive.google.com/file/d/1eQ_Oav8pxMJ-55qwwyRurjS_dyKgFGqZ/view seems have some checks.. log:
> 
> ```
> [2022.08.27-05.35.35:282][  0]LogDLSS: FDLSSModule::StartupModule Enter
> [2022.08.27-05.35.35:282][  0]LogDLSS: PluginBaseDir ../../../CitySample/Plugins/DLSS
> [2022.08.27-05.35.35:302][  0]LogDLSS: NGXBinariesDir ../../../CitySample/Plugins/DLSS/Binaries/ThirdParty/Win64/
> [2022.08.27-05.35.35:303][  0]LogDLSS: GDynamicRHIName NVIDIA D3D12
> [2022.08.27-05.35.35:313][  0]LogDLSS: Plugin settings: NGXAppId = 0
> [2022.08.27-05.35.35:317][  0]LogDLSS: Warning: NGX Application ID not specified, using the Project ID by default.
> [2022.08.27-05.35.35:319][  0]LogDLSSNGXRHI: FNGXRHIModule::StartupModule Enter
> [2022.08.27-05.35.35:321][  0]LogDLSSNGXRHI: FNGXRHIModule::StartupModule Leave
> [2022.08.27-05.35.35:327][  0]LogDLSSNGXRHI: Searching for custom and generic DLSS binaries
> [2022.08.27-05.35.35:328][  0]LogDLSSNGXRHI: NVIDIA NGX DLSS binary nvngx_dlss.dll not found in search path E:\a4\CitySample_51_DLSS_Cinematic\CitySample\Binaries\ThirdParty\NVIDIA\NGX\Win64\
> [2022.08.27-05.35.35:329][  0]LogDLSSNGXRHI: NVIDIA NGX DLSS binary nvngx_dlss.dll not found in search path E:\a4\CitySample_51_DLSS_Cinematic\CitySample\Binaries\Win64\Binaries\ThirdParty\NVIDIA\NGX\Win64\
> [2022.08.27-05.35.35:330][  0]LogDLSSNGXRHI: NVIDIA NGX DLSS binary nvngx_dlss.dll found in search path E:\a4\CitySample_51_DLSS_Cinematic\CitySample\Plugins\DLSS\Binaries\ThirdParty\Win64\
> [2022.08.27-05.35.35:332][  0]LogDLSSNGX: [SDK]: [2022-08-27 07:35:35] [NGXSafeInitializeLog:130] App logging hooks successfully initialized
> [2022.08.27-05.35.35:346][  0]LogDLSSNGX: [SDK]: [2022-08-27 07:35:35] [NGXGetPathUsingQAI:127] Path to driverStore found using QAI: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_800c5375bcee0134
> [2022.08.27-05.35.35:883][  0]LogDLSSNGX: [Core]: [2022-08-27 07:35:35] [NGXSafeInitializeLog:130] App logging hooks successfully initialized
> [2022.08.27-05.35.35:996][  0]LogDLSSNGX: [Core]: [2022-08-27 07:35:35] [NGXCheckHardwareSupportUsingINF:212] error: unsupported hardware detected
> [2022.08.27-05.35.36:002][  0]LogDLSSNGXD3D12RHI: NVSDK_NGX_D3D12_Init_with_ProjectID(ProjectID = 914301364FA2BD41AB81DA86AC490783, EngineVersion=5.1, APIVersion = 0x14, Device=0000012D6C4A1040) -> (3134193665 NVSDK_NGX_Result_FAIL_FeatureNotSupported)
> [2022.08.27-05.35.36:086][  0]LogDLSSNGX: [Core]: [2022-08-27 07:35:36] [NGXCheckHardwareSupportUsingINF:212] error: unsupported hardware detected
> [2022.08.27-05.35.36:106][  0]LogDLSSNGXD3D12RHI: NVSDK_NGX_D3D12_Init_with_ProjectID(ProjectID = 914301364FA2BD41AB81DA86AC490783, EngineVersion=5.1, APIVersion = 0x13, Device=0000012D6C4A1040) -> (3134193665 NVSDK_NGX_Result_FAIL_FeatureNotSupported)
> [2022.08.27-05.35.36:111][  0]LogDLSSNGXD3D12RHI: NVSDK_NGX_D3D12_Init (Log C:/Users/rtfss/AppData/Local/CitySample/Saved/Logs/NGX/NGX_2022.08.27-07.35.35_478E6EB7483B6E0FFCA9559322110D8C) -> (3134193665 NVSDK_NGX_Result_FAIL_FeatureNotSupported)
> [2022.08.27-05.35.36:113][  0]LogDLSS: DLSS not supported by the NVIDIA D3D12 RHI in the NGXD3D12RHI module at runtime
> [2022.08.27-05.35.36:113][  0]LogDLSS: NVIDIA NGX DLSS supported 0
> [2022.08.27-05.35.36:114][  0]LogDLSS: FDLSSModule::StartupModule Leave
> ```

From what I see in the plugin source code, the DLSS loading procedure is the same as in UE4 (I'll check it later in game). According to the log, the game is trying to load `nvngx_dlss.dll` instead of `nvngx.dll`, are you sure you activated `EnableSignatureOverride.reg`?

**Comment by MOVZX** [comment]
### This UE5 Demo is torture

`R9 5950X + RX 6800 XT`

**Ultra**
![image](https://user-images.githubusercontent.com/3374397/187028746-b9979bff-4304-4992-90bb-31f223943d19.png)

**Upscaling: OFF**
![image](https://user-images.githubusercontent.com/3374397/187028776-9e5d8087-ea39-4754-808e-b77cab4eb216.png)

**Upscaling: Ultra Quality**
![image](https://user-images.githubusercontent.com/3374397/187028784-7f59207d-d228-4605-b71b-20a2dff19dfb.png)

**Upscaling: Quality**
![image](https://user-images.githubusercontent.com/3374397/187028805-e98d4d30-9f00-4b30-869f-29e1992aa29a.png)

**Upscaling: Balanced**
![image](https://user-images.githubusercontent.com/3374397/187028817-136933e0-a128-484c-a30b-2f312cb55645.png)

**Upscaling: Performance**
![image](https://user-images.githubusercontent.com/3374397/187028824-76e94566-cea4-42b7-8157-1cc06c2d8ad1.png)

**Upscaling: Ultra Performance**
![image](https://user-images.githubusercontent.com/3374397/187028847-109c267b-f4ee-46fe-8fe7-a170a298f7a2.png)

**Comment by oscarbg** [comment]
@lnfecteDru thanks for looking into it..

in the meanwhile I also was able to fix it also by changing:
E8 04 D7 C4 01 84 C0 75 2D
E8 04 D7 C4 01 84 C0 74 2D
so changed jne with je, fix it for me but then remember a complete fix is change with jmp instruction inconditionally..

this fixes the IsRHIDeviceNVIDIA(void) in DLSS..
but then as I have a system with NV and AMD GPU even if I disable the NV card from device manager seems the DLSS static libraries linked into exe search for Nvidia installed drivers on Driverstore folder and use this _nvngx.dll breaking DLSS support..
the UNIQUE way to fix this is by putting cyberfsr2 nvngx.dll in the game folder "CitySample_51_DLSS_Cinematic\CitySample\Binaries\Win64"
seems Nvidia left a way for users to use update nvngx.dll by putting in game exe folder NOT in thirdparty (CitySample_51_DLSS_Cinematic\CitySample\Plugins\DLSS\Binaries\ThirdParty\Win64\)
this is important!!
this may be required by people also with old NV GPUs not supporting DLSS as they have a NV driver installed..

**Comment by oscarbg** [comment]
Hi,

even this is a issue about DLSS let me talk about UE5 D3D12 render issues on AMD cards.. 

in fact I make a BIG CLAIM: using this DLSS hacked support right now is a MUST for running UE5 content rendered correctly on AMD GPUs (at least currently).. I mean using D3D12 and also authored to use SM6 backed (needed for Lumen anyway?).. this demo is an example of a UE5 D3D12 SM6 only compiled demo.. i.e. forcing -d3d11 or -sm5 demo will not run..
the example is @MOVZX (Upscaling: OFF) screenshoot (so no DLSS)..

@MOVZX have you noticed running the demo without DLSS enabled, (your Upscaling: OFF screenshot), has rendering issues, big "pixelation" effects, even tough it should be better than or equal to DLSS ultra quality, right? notice especially around the girl you control..
before hacking DLSS support, I had noticed that running on RX Vega D3D12, and thinked it was a Vega HW issue, or some driver issue.. I see now RDNA2 cards are also affected which is sad..
also noticed that running under VKD3D on Linux under RADV the issues aren't present.. (might require running with -novendordevice)
under Windows VKD3D for AMD also needs a hack for enabling SM6.6 support because of missing NV_compute_derivatives..
but even then AMD Windows Vulkan driver +VKD3D doesn't boot the demo..

seems old NV hardware without DLSS has no rendering artifacts under D3D12 SM6(.6) mode..

would be nice to see with Intel DG2 hardware like A380 if this demo without DLSS has rendering issues..

**Comment by RareMv** [comment]
Tested another Unreal 4 game: **Observer System Redux**

FSR 2.1.1 from the CB77 Nexus mod works like a native implementation (version 0.8.0-beta2). Boost performance with ZERO perceived image quality loss. Zero artefacting or ghosting. 10/10 implementation.

**Comment by MOVZX** [comment]
> Tested another Unreal 4 game: **Observer System Redux**
> 
> FSR 2.1.1 from the CB77 Nexus mod works like a native implementation (version 0.8.0-beta2). Boosted performance with ZERO perceived image quality loss. Zero artefacting or ghosting. 10/10 implementation.

### Look at this comparison images

### NATIVE FSR
![image](https://user-images.githubusercontent.com/3374397/190927107-5f3c757c-b203-4aef-8bbb-0ef848036177.png)

### CyberFSR 0.8.0-beta2
![image](https://user-images.githubusercontent.com/3374397/190927129-a985d859-1c73-429b-b225-962fda37a4ab.png)

It's a day and night difference.

**Comment by paulober** [comment]
Has anyone here tried it with `The Ascent` (also UE4 and does only support DLSS2)?

**Comment by spajdrEX** [comment]
> Has anyone here tried it with `The Ascent` (also UE4 and does only support DLSS2)?

It does work as long you use 0.8.0 beta 2. But there will be ghosting/smearing.

**Comment by ishitatsuyuki** [comment]
If you're wondering why the `SceneColorFormat` hack is needed, it's because some (or all?) versions of DLSS UE plugin has a bug where the InputColor buffer is in the wrong resource state (`D3D12_RESOURCE_STATE_RENDER_TARGET`). AMD hardware applies compression that are incompatible with SRV use, and using `SceneColorFormat=5` works only because F32 is not compressed at all. It also comes at a performance cost.

It might be worth trying injecting a transition to `D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE` before FSR dispatch, then after the dispatch transition it back to `D3D12_RESOURCE_STATE_RENDER_TARGET` so that the engine don't get confused.
