### ISSUE TITLE
F1 2022

### ISSUE THREAD

**Issue by SaulGoodman1337** [PotatoOfDoom/CyberFSR2#18]
Hi,
Would it be possible to port the whole thing to F1 2022 and if so, what is the effort ?
Greetings Daniel

**Comment by ZachAR3** [comment]
I would just try it with F1 22 since it works with most games that have DLSS which it has, and see if it works already.

**Comment by PotatoOfDoom** [comment]
Well the thing is: F1 22 already has FSR2 built-in. It is just hidden: You can enable it by setting the proper quality presets via the FSR1 setting in the options, then exiting the game, going into the config file in `%USERPROFILE%\Documents\my games\F1 22\hardwaresettings\hardware_settings_config.xml`. Look for the the `fsr` property and set it to 0 and afterwards set the `fsr2` one to 1. Save the file and you should be able to play the game with FSR2 (you'll notice the improved quality and ghosting behind cars). Just don't go in the options menu afterwards (this will reset the FSR2 toggle and you will have to go into the config files again.)

**Comment by SaulGoodman1337** [comment]
Glad we talked about it ! :)
I'll try it out right away.
