### ISSUE TITLE
Motion Blur crashes Cyberpunk.

### ISSUE THREAD

**Issue by E3rok** [PotatoOfDoom/CyberFSR2#22]
### Motion Blur crashes Cyberpunk with the mod on

After thorough testing, I finally found what was causing issues on amd/rdna2 cards:
Screen scrambling
The borders of the game being blurry (and looked like they are rendering something from atop the screen on the bottom and reverse for the top etc.)
Crashing at 4k Resolution

Its all specific to motion blur, no matter which setting. Why this happens I don't know, and I'm not sure if this is even fixable, but I just wanted to let you know where the crashes are coming from.

**Comment by PotatoOfDoom** [comment]
Thanks for the info but this is already on my known issues list on nexusmods. I can't fix the issue because I just can't reproduce the bug with the gpus I own.
