### ISSUE TITLE
cant compile - when next release?

### ISSUE THREAD

**Issue by Benman2785** [PotatoOfDoom/CyberFSR2#28]
Hey, when i compile i get 3 dlls and when i stick them into DL2 folder DLSS doesnt show up on my RX 580

when will there be a new release?

**Comment by lnfecteDru** [comment]
Which dlls you get? If it is "ffx_fsr2_api_dx12_x64.dll", "ffx_fsr2_api_vk_x64.dll" and "ffx_fsr2_api_x64.dll" then you also need to compile the "CyberFSR2" project which will build "nvngx.dll". Then you need to copy it next to the 3 dlls.

**Comment by Benman2785** [comment]
mh, i try again and check

**Comment by Ryusennin** [comment]
You can also try the latest builds:
https://github.com/PotatoOfDoom/CyberFSR2/actions
