### ISSUE TITLE
[Request] prboom-plus-rt support

### ISSUE THREAD

**Issue by IDDQD1337** [PotatoOfDoom/CyberFSR2#29]
I think you can make compatibility with prboom-plus-rt when you switch from off to quality, the game gives an error!

![Capture001](https://user-images.githubusercontent.com/28530397/182374474-80fa43b6-9ca4-4035-93c4-a401afb5ba9b.png)

**Comment by MOVZX** [comment]
The DLL produced by GitHub Action is broken for Vulkan, you need to compile it yourself.

**I compiled it for you to try if you need it:**
[DLSS-VK.zip](https://github.com/PotatoOfDoom/CyberFSR2/files/9245160/DLSS-VK.zip)

**Running very well under Radeon GPU here:**
![image](https://user-images.githubusercontent.com/3374397/182459818-3563ad69-cff1-467f-9549-19d614d82009.png)

**Comment by PotatoOfDoom** [comment]
I fixed the Vulkan compatibility in ba346fa6788a2183ecdb5c1eeccf8b03b97b6561. So any future build will support DX12 and Vulkan at the same time.
