### ISSUE TITLE
Support for (future) open Intel XeSS SDK..

### ISSUE THREAD

**Issue by oscarbg** [PotatoOfDoom/CyberFSR2#35]
Hi,
first note this SDK is not released yet but should be released soon (this summer?)..
this maybe a request for a new project (DLSS2XESS) or not depending if this project plans supporting DLSS via both FSR2 and DLSS or better a separate project..
anyway makes sense as maybe more optimized at least for Intel DG2 vs FSR2.. also depending on the quality absolute factor and quality/perf tradeoff maybe interesting for other GPUs..
sorry for opening so earlier but had this thought and wanted to start a discussion to see if there is potential interest..
EDIT: maybe D3D12 only as Intel mentions broad compat support for GPUs with SM6.4..

thanks..

**Comment by PotatoOfDoom** [comment]
Well, I doubt Intel will make the source code available until sometime next year. Also, Intel hasn't really released any (useable) information about xess. So I don't have anything to work with. I will implement when they actually release something, but I don't think there's anything to talk about or do until that actually happens.

**Comment by oscarbg** [comment]
@PotatoOfDoom code is here!:
https://github.com/intel/xess/releases/tag/v1.0.0

**Comment by MOVZX** [comment]
CyberXeSS is available on official Discord Channel:

https://discord.com/channels/995299945492008990/995299946028871735/1024429580892774540
