### ISSUE TITLE
How can depurate it?

### ISSUE THREAD

**Issue by Milor123** [PotatoOfDoom/CyberFSR2#36]
Hi dude, I need know if it mod is active in a game, some games dont show DLSS option directly in menu, need manually config, but i am not sure if DLSS is active, how can i check it? Thank you veru much

**Comment by MOVZX** [comment]
Which games doesn't show DLSS option when it's turned on?

**Comment by Milor123** [comment]
> Which games doesn't show DLSS option when it's turned on?

I am sorry dear, my mistake, I've read today in a FSR2 Discord channel where they  talked about this mod not working on **dx11**, and the game in the which i was testing it, **dont use dx12**, only 11, is **The Elder Scrolls Online**

Thank you very much for you reply

**Comment by MOVZX** [comment]
FSR is not possible for DX11 games because AMD doesn't opensource it.

**Comment by WubTheGame** [comment]
> FSR is not possible for DX11 games because AMD doesn't opensource it.

Sorry to butt in, but what do you mean AMD doesn't open source it? FSR 1 and 2 are both open source on Github. Do you mean FSR isn't available for DX11?
https://github.com/GPUOpen-Effects/FidelityFX-FSR
https://github.com/GPUOpen-Effects/FidelityFX-FSR2

**Comment by TheRazerMD** [comment]
FSR2 is currently only open-sourced for DX12 and Vulkan. DX11 source is unavailable and only available to devs on contact.
