### ISSUE TITLE
FSR 2.1 update? ;)

### ISSUE THREAD

**Issue by Benman2785** [PotatoOfDoom/CyberFSR2#38]
??? ;)

**Comment by Benman2785** [comment]
you already did it - sry to bother ;)

**Comment by TheRazerMD** [comment]
It did remove some of the ghosting and improved temporal stability. Can’t get rid of all ghosting magically tho. Still needs refining.

**Comment by Benman2785** [comment]
its much better - i use the mod for DL2 and Cyberpunk - both had ghosting issues that are nearly gone now ;)
