### ISSUE TITLE
Fallout games support

### ISSUE THREAD

**Issue by LichLord91** [PotatoOfDoom/CyberFSR2#43]
Hello stumbled upon this and was wondering if there's any interest to get this working for Fallout series like 3/new vegas/ and 4? I have a steam deck and would love to get this working for these games. Happy to test or figure out how to get this working. I'm a systems engineer by trade so comfortable with making custom builds/ getting my hands dirty in linux.

**Comment by Ryusennin** [comment]
DLSS2FSR is a DLSS to FSR emulator. It is not a mod to implement FSR in games.
To my knowledge, Fallout 4 (let alone 3) doesn't have any DLSS support.

**Comment by LichLord91** [comment]
Ahh sorry for the misunderstanding , thanks!
