### ISSUE TITLE
Host the binaries on github

### ISSUE THREAD

**Issue by RIKLAVIEGASINTRODUCTION** [PotatoOfDoom/CyberFSR2#44]
Would this be possible? I'd rather not register for nexusmods.

**Comment by PotatoOfDoom** [comment]
You can find the binaries for the universal version in the github actions section of this repository. The version with cyberpunk-specific optimizations is nexusmods exclusive for now.

**Comment by RIKLAVIEGASINTRODUCTION** [comment]
> You can find the binaries for the universal version in the github actions section of this repository. The version with cyberpunk-specific optimizations is nexusmods exclusive for now.

Thanks for the tip. Didn't see anything in the releases tab on the sidebar and there's nothing in the README about the universal version just a link to the nexus. I downloaded the universal versions from Actions and it seems it doesn't have an .ini nor the .reg files do they get generated when I start the game or something?

**Comment by PotatoOfDoom** [comment]
they are in the root folder of this repository.
