### ISSUE TITLE
not woking on A Plague Tale- Requiem - Windows

### ISSUE THREAD

**Issue by lingjiamian** [PotatoOfDoom/CyberFSR2#45]
![A Plague Tale_ Requiem - Windows 2022_10_18 0_27_24](https://user-images.githubusercontent.com/18097417/196233375-e9f0870d-8327-40a6-8757-62ce02c39ec7.png)
![QQ图片20221018003642](https://user-images.githubusercontent.com/18097417/196234015-3043a5e8-f764-4a70-878e-63e7634f389d.png)
no dlss option
gpu: rx6600
platform: xbox pc

**Comment by MOVZX** [comment]
Upload APT2_WinStore.x64.Submission.exe here, I'll try to make the DLSS unlocker for Game Piss version.

**Comment by lingjiamian** [comment]
[APT2_WinStore.x64.Submission.zip](https://github.com/PotatoOfDoom/CyberFSR2/files/9806560/APT2_WinStore.x64.Submission.zip)

**Comment by LeauDesPates000** [comment]
hey, im very interested at having the fuul folder when u have done it, ( like when its working ), ty !

**Comment by Uberlime** [comment]
+1, doesn't work on anything pre-Turing on the Nvidia side either, I dream of a universal bypass, a bit like "Lossless Scaling Build 9275497"...

**Comment by zhizheamd** [comment]
https://www.nexusmods.com/marvelsspidermanremastered/mods/683
来自[MOVZX](https://github.com/MOVZX)

**Comment by zhizheamd** [comment]
抱歉(。・＿・。)ﾉI’m sorry~；昨晚发的那个链接有问题。 
这是新的 https://www.nexusmods.com/aplaguetalerequiem/mods/7?tab=description

**Comment by Uberlime** [comment]
Nice, but you mean https://www.nexusmods.com/aplaguetalerequiem/mods/9?tab=description ("The other guy had stolen the files from this author's github page and was impersonating him both on nexus and even on youtube")
Also a useful link : Official CyberFSR Discord Server
https://discord.gg/2JDHx6kcXB

**Comment by zhizheamd** [comment]
> 很好，但你的意思是https://www.nexusmods.com/aplaguetalerequiem/mods/9?tab=description（“另一个人从作者的 github 页面窃取了文件，并在 nexus 甚至 youtube 上冒充他” ) 也是一个有用的链接：官方 Cyber​​FSR Discord 服务器 https://discord.gg/2JDHx6kcXB

The creator of the second MOD, misunderstood MOVZX.
Mods made by MOVZX have now reopened for access.
