### ISSUE TITLE
Version selection method

### ISSUE THREAD

**Issue by TuTAH1** [PotatoOfDoom/CyberFSR2#47]
I tryed 0.1, 0.2, 0.6, 0.7.7 and 0.8.0 beta4 versions with Alan Wake Remastered, all not working with my GTX 1080 (first one crashes, other gives black screen with only HUD visible when DLSS enabled). Should I keep trying other version or it would be useless? If it's not useless to try other version, in what order should I do it (to except very simmilar versions that are useless to test both)?

**Comment by spajdrEX** [comment]
Nothing you can do about it. Game uses the same gfx engine as the game "Control" which have similar issues.
