### ISSUE TITLE
Support for Vulkan DLSS games?

### ISSUE THREAD

**Issue by oscarbg** [PotatoOfDoom/CyberFSR2#6]
Hi,
thanks for your work!
seeing people are trying to use your mod on other DLSS games like RDR2.. but seeing your mod started for Cyberpunk which is a DX12 game I guess support for native Vulkan games using DLSS will require some work, right?
I mean games like: DOOM Eternal, No Man’s Sky, and Wolfenstein: Youngblood.
At least FSR 2.0 code drop seems to have Vulkan support also so can eventually be added to your DLSS2FSR2 wrapper as I may call it :-)
hope someone wants to work on it..

**Comment by RealIndica** [comment]
Check out my fork of this project, it supports Vulkan.

**Comment by mnxn** [comment]
Great work @RealIndica!

Any chance you can make a PR for adding Vulkan support to this repository?

**Comment by RealIndica** [comment]
> Great work @RealIndica!
> 
> Any chance you can make a PR for adding Vulkan support to this repository?

I would love to, but I have no idea how to create another fork due to already having my RDR2 fork here.

**Comment by PotatoOfDoom** [comment]
Don't worry. I can add it myself. It doesn't seem too complicated.

**Comment by RealIndica** [comment]
> Don't worry. I can add it myself. It doesn't seem too complicated.

It's not but you might find game-dependent issues with ffxGetTextureResourceVK when trying to load an FfxResource to a dispatch parameter when the arguments for the  ffxGetTextureResourceVK are invalid/null; it will just crash on EvaluateFeature. That's why for transparencyAndComposition a null FfxResource is used. RDR2 doesn't seem to have transparencyAndComposition for Vulkan 🤷

**Comment by SpaceGoat04** [comment]
> Check out my fork of this project, it supports Vulkan.

Does your fork work on other titles like this mod or was it built specifically for RDR2 and therefore only works on it? Great work btw

**Comment by RealIndica** [comment]
> > Check out my fork of this project, it supports Vulkan.
> 
> Does your fork work on other titles like this mod or was it built specifically for RDR2 and therefore only works on it? Great work btw

PotatoOfDoom has added Vulkan to this version now so should work in Vulkan games.
