### ISSUE TITLE
Fork for XeSS

### ISSUE THREAD

**Issue by paulober** [PotatoOfDoom/CyberFSR2#69]
Hi, i would like to use this project as a base for a XeSS drop in replacement of DLSS in Cyberpunk 2077.
Any hints were to start and if this is even possible to do with this repo?

**Comment by juzi5201314** [comment]
hi, thanks for your work, I noticed you made two commits for this, but it stopped after that, is there something holding you back?

**Comment by Rigelstars** [comment]
> hi, thanks for your work, I noticed you made two commits for this, but it stopped after that, is there something holding you back?

我找遍网络都找不到xess的mod，太难受了

**Comment by paulober** [comment]
@Rigelstars 
说英语!
1. 没有适用于CP77的XeSS模型存在。
2. 他们已经在游戏中正式实施了XeSS，如果你找不到它就不要玩了。
3. 他说的是我对CyberFSR2 repo的分叉，它试图实现XeSS版本，但我没有完成，因为我认为他们会在下次更新时实现，所以没有必要。

**Comment by Rigelstars** [comment]
> @Rigelstars 
> 说英语!
> 1. 没有适用于CP77的XeSS模型存在。
> 2. 他们已经在游戏中正式实施了XeSS，如果你找不到它就不要玩了。
> 3. 他说的是我对CyberFSR2 repo的分叉，它试图实现XeSS版本，但我没有完成，因为我认为他们会在下次更新时实现，所以没有必要。

thank sir
